language: haxe

os: linux
dist: trusty

haxe:
  - development
  - "4.1.3"

install:
  - yes | haxelib install tests.hxml
  - haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
  - haxelib git heaps https://github.com/HeapsIO/heaps.git
  - haxelib install hlsdl
  - haxelib list

script:
  - haxe tests/js.hxml
  - haxe tests/neko.hxml
  - haxe genSamples.hxml

notifications:
  email:
    on_success: never
    on_failure: always